### ISSUE TITLE
Support graphql-ruby v2.x

### ISSUE THREAD

**Issue by michiomochi** [rrreeeyyy/graphql-schema-directive-constraint#1]
Thanks for great gem!
Are you planning to support graphql-ruby v2.x?

**Comment by rrreeeyyy** [comment]
Now we use graphql-ruby 1.x internally. But it does not change the fact that we should update to 2.x some day. So I will do my best to support v2.x in my spare time. Or if you send a pull-request, I will check it.

**Comment by michiomochi** [comment]
OK, thank you!
I will try to support v2 👍
